### ISSUE TITLE
Rebuild Models in U8StarterKit.Web.Models.Umbraco Using Models Builder 8.1.0

### ISSUE THREAD

**Issue by paulsterling** [mjbarlow/Umbraco-8-Bulma-Starter-Kit#2]
After an upgrade to 8.1.0 the site renders with the error

```
Cannot bind source content type Umbraco.Web.PublishedCache.NuCache.PublishedContent to model type U8StarterKit.Web.Models.Umbraco.Home
```

I believe, due to updates in Umbraco `IPublishedContent` and Bulma Starter Kit's custom models approach, all the custom models will need to be regenerated against the new `ModelsBuilder` and `IPublishedContent` in Umbraco 8.1.0. 

There may be other places where updates will be required as well as 8.1.0 introduced a number of breaking changes:
https://our.umbraco.com/documentation/Getting-Started/Setup/Upgrading/v81-ipublishedcontent-changes

I'll try to get to this, but wanted to capture the issue in case others had input or want to get started on the updates.

**Comment by Shaggy2408** [comment]
Is this issue Also related to this post

https://our.umbraco.com/packages/starter-kits/bulma-starter-kit/bulma-starter-kit-for-v8/98417-falink-does-not-work

**Comment by cherylcarpenter** [comment]
For my team, the kit as distributed in the package was never going to work for us, as we need the modelsbuilder to work and could not do so with the distributed model/dll version.
I downloaded source files from this repo, used the models builder in the AppData mode, and we've not had any issues upgrading to 8.1.0. For us, the repo version has worked much better than the package on umbraco. But our skill set is more frontend.   

That said, falink gave us lots of fits at first due to not having null checks. As we changed the templates for !=null everywhere, falink has been fine.

Hope you don't mind my 2cents. When we went with Umbraco 8 a few months back, this was the most robust kit to start from and it is serving us weel.

**Comment by paulsterling** [comment]
Hi @cherylcarpenter -
That sounds like a solid approach...along the lines of what I've been considering as well. Would you be willing to create a new branch and send a PR to this repo with your changes? Perhaps that could jumpstart the process to get the starterkit moved over to models builder by default. I'd love to see that for one:
https://twitter.com/paulsterling/status/1136377896006590465

**Comment by cherylcarpenter** [comment]
> Would you be willing to create a new branch and send a PR to this repo with your changes?

oh hah, i can try given a day or two-- I'm really a hack :) I liked the 3-projects in one solution seen here, and kept fiddling til it worked with a blank database lol. 
Here's my webconfig
    add key="Umbraco.ModelsBuilder.Enable" value="true"
    add key="Umbraco.ModelsBuilder.ModelsMode" value="AppData" 
    add key="Umbraco.ModelsBuilder.ModelsNamespace" value="MyProject.Core.Models" 
    add key="Umbraco.ModelsBuilder.ModelsDirectory" value="~/../MyProject.Core/Models" 
    add key="Umbraco.ModelsBuilder.AcceptUnsafeModelsDirectory" value="true" 

And yes just search and replace the namespaces throughout. My goal being to get to my blank install Admin side to push the models builder button. I'll see what i can branch to here. 

PS-- oh yeah, i had a blank project, installed Umbraco, installed the U8StarterKit so that it populated my database, then started over with this source code. So, as a complete hack, i have no idea how to start with models and get it 'into' a database in the form of content. This was the hacky step.

**Comment by cherylcarpenter** [comment]
> PS--

oh yeah, AND make sure the FaLinks dll is 'Included' in the VS project.
VisualStudio/.NET really are from hell for the front end developer.

**Comment by cherylcarpenter** [comment]
**I found the gotcha, i apologize for the rabbit hole**. I had indeed updated to 8.1 and everything worked. It breaks when generating any new models with the updated ModelsBuilder. Reading through the breaking changes (in minor revision numbers again) on IPublishedContent. I'm guessing there is needed updates in the GetFaLinks as HasValue() no longer works on the FaLinks object. 
And that's the extent of my skill level and I will downgrade to v8, until the FaLinks rewritten or we work round. 
Thanks.

**Comment by mjbarlow** [comment]
Thanks guys, I've updated the Starter Kit to work with Umbraco version v8.2.0, also the models mode is now set to DLL, so the models are no longer included in the main project Dll and can be regenerated as required. Thanks for using my starter kit! :)

**Comment by Shaggy2408** [comment]
Hi there,

I am getting this error

[cid:image004.png@01D58B60.04301940]


[cid:image005.png@01D58B60.04301940]
Shahid Mahmood Hussain
Senior Solution Architect, Dynamics 365
Mobile: +45 26 85 74 97

Abakion A/S | Vibenshuset, Lyngbyvej 2 | 2100 København Ø | Danmark | + 45 70 23 23 17
Abakion.dk<https://abakion.dk> | Abakion.com<https://abakion.com> | Facebook<https://www.facebook.com/abakion.dk> | LinkedIn<https://www.linkedin.com/company/abakion-as>

**Comment by Shaggy2408** [comment]
Hi There,

i am getting this error

![image](https://user-images.githubusercontent.com/10222061/67587147-865b7e00-f753-11e9-9fce-a91431062c5a.png)
